version: '2'
services:
    webserver:
        build:
            context: ./
            dockerfile: config/webserver.docker
        container_name: ${COMPOSE_PROJECT_NAME}_webserver
        volumes:
            - project:/var/www:rw
        ports:
            - "${WEB_PORT}:80"
        links:
            - app
    app:
        image: shhetri/laravel-php-alpine:php7
        container_name: ${COMPOSE_PROJECT_NAME}_app
        volumes:
            - project:/var/www:rw
        links:
            - postgres
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=postgres"
    postgres:
        image: kiasaki/alpine-postgres:9.5
        container_name: ${COMPOSE_PROJECT_NAME}_postgres
        environment:
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "POSTGRES_DB=${POSTGRES_DB}"
        ports:
            - "54321:5432"
volumes:
  project:
    external:
        name: ${PROJECT_CONTAINER_NAME}
